-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-12-12 13:20:17 CET
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE book 
    ( 
     id_book     INTEGER  NOT NULL , 
     title       VARCHAR2 (255)  NOT NULL , 
     author      VARCHAR2 (255)  NOT NULL , 
     genre       VARCHAR2 (100) , 
     description VARCHAR2 (4000) , 
     created_at  DATE DEFAULT CURRENT_TIMESTAMP , 
     created_by  INTEGER , 
     updated_at  DATE , 
     updated_by  INTEGER 
    ) 
    LOGGING 
;

ALTER TABLE book 
    ADD CONSTRAINT book_PK PRIMARY KEY ( id_book ) ;

CREATE TABLE reading_status 
    ( 
     id_status INTEGER  NOT NULL , 
     name      VARCHAR2 (50)  NOT NULL 
    ) 
    LOGGING 
;

ALTER TABLE reading_status 
    ADD CONSTRAINT reading_status_PK PRIMARY KEY ( id_status ) ;

ALTER TABLE reading_status 
    ADD CONSTRAINT INDEX_1 UNIQUE ( name ) ;

CREATE TABLE review 
    ( 
     id_review  INTEGER  NOT NULL , 
     id_user    INTEGER  NOT NULL , 
     id_book    INTEGER  NOT NULL , 
     rating     INTEGER , 
     content    VARCHAR2 (4000) , 
     created_at DATE DEFAULT CURRENT_TIMESTAMP 
    ) 
    LOGGING 
;

ALTER TABLE review 
    ADD 
    CHECK (rating BETWEEN 1 AND 10) 
;

ALTER TABLE review 
    ADD CONSTRAINT review_PK PRIMARY KEY ( id_review ) ;

ALTER TABLE review 
    ADD CONSTRAINT INDEX_1 UNIQUE ( id_user , id_book ) ;

CREATE TABLE role 
    ( 
     id_role    INTEGER  NOT NULL , 
     name       VARCHAR2 (50)  NOT NULL , 
     is_active  NUMBER , 
     created_at DATE DEFAULT CURRENT_TIMESTAMP 
    ) 
    LOGGING 
;

ALTER TABLE role 
    ADD CONSTRAINT role_PK PRIMARY KEY ( id_role ) ;

ALTER TABLE role 
    ADD CONSTRAINT INDEX_1 UNIQUE ( name ) ;

CREATE TABLE "user" 
    ( 
     id_user    INTEGER  NOT NULL , 
     login      VARCHAR2 (50)  NOT NULL , 
     password   VARCHAR2 (255)  NOT NULL , 
     email      VARCHAR2 (100) , 
     created_at DATE DEFAULT CURRENT_TIMESTAMP , 
     updated_at DATE 
    ) 
    LOGGING 
;

ALTER TABLE "user" 
    ADD CONSTRAINT user_PK PRIMARY KEY ( id_user ) ;

ALTER TABLE "user" 
    ADD CONSTRAINT INDEX_1 UNIQUE ( login ) ;

CREATE TABLE user_book 
    ( 
     id_user          INTEGER  NOT NULL , 
     id_book          INTEGER  NOT NULL , 
     id_status        INTEGER  NOT NULL , 
     progress         INTEGER , 
     start_date       DATE , 
     planned_end_date DATE 
    ) 
    LOGGING 
;

ALTER TABLE user_book 
    ADD 
    CHECK (progress BETWEEN 0 AND 100) 
;

ALTER TABLE user_book 
    ADD CONSTRAINT user_book_PK PRIMARY KEY ( id_user, id_book ) ;

CREATE TABLE user_role 
    ( 
     id_user     INTEGER  NOT NULL , 
     id_role     INTEGER  NOT NULL , 
     assigned_at DATE DEFAULT CURRENT_TIMESTAMP 
    ) 
    LOGGING 
;

ALTER TABLE user_role 
    ADD CONSTRAINT user_role_PK PRIMARY KEY ( id_user, id_role ) ;

ALTER TABLE book 
    ADD CONSTRAINT book_user_FK FOREIGN KEY 
    ( 
     created_by
    ) 
    REFERENCES "user" 
    ( 
     id_user
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE book 
    ADD CONSTRAINT book_user_FKv1 FOREIGN KEY 
    ( 
     updated_by
    ) 
    REFERENCES "user" 
    ( 
     id_user
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE review 
    ADD CONSTRAINT review_book_FK FOREIGN KEY 
    ( 
     id_book
    ) 
    REFERENCES book 
    ( 
     id_book
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE review 
    ADD CONSTRAINT review_user_FK FOREIGN KEY 
    ( 
     id_user
    ) 
    REFERENCES "user" 
    ( 
     id_user
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE user_book 
    ADD CONSTRAINT user_book_book_FK FOREIGN KEY 
    ( 
     id_book
    ) 
    REFERENCES book 
    ( 
     id_book
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE user_book 
    ADD CONSTRAINT user_book_reading_status_FK FOREIGN KEY 
    ( 
     id_status
    ) 
    REFERENCES reading_status 
    ( 
     id_status
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE user_book 
    ADD CONSTRAINT user_book_user_FK FOREIGN KEY 
    ( 
     id_user
    ) 
    REFERENCES "user" 
    ( 
     id_user
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE user_role 
    ADD CONSTRAINT user_role_role_FK FOREIGN KEY 
    ( 
     id_role
    ) 
    REFERENCES role 
    ( 
     id_role
    ) 
    NOT DEFERRABLE 
;

ALTER TABLE user_role 
    ADD CONSTRAINT user_role_user_FK FOREIGN KEY 
    ( 
     id_user
    ) 
    REFERENCES "user" 
    ( 
     id_user
    ) 
    NOT DEFERRABLE 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             7
-- CREATE INDEX                             0
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
